#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
 
# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/aites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service ngix restart
