#!/bin/bash

# Check if Nginx is running
nginx_status=$(service nginx status)

# Start Nginx if it's not running
if [[ $nginx_status != *"active (running)"* ]]; then
    service nginx start
fi

# Ensure Nginx is configured to listen on port 80
nginx_config="/etc/nginx/sites-available/default"
if ! grep -q "listen 80" "$nginx_config"; then
    sed -i '/listen 80/ c\    listen 80;' "$nginx_config"
fi

# Restart Nginx to apply changes
service nginx restart

